site_name: ecommerceapi
site_description: Building an Ecommerce API using Django and Django Rest Framework.
repo_url: https://github.com/BikoCodes/e-commerce-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/BikoCodes">BikoCodes</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
